
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 15 17:57:27 BOT 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Salto_Linea = 4;
  public static final int Literal = 3;
  public static final int Tab = 2;
  public static final int ERROR = 5;
  public static final int error = 1;
  public static final int Calificacion = 6;
  public static final int EOF = 0;
}

